#!/bin/bash
# vim: set ft=sh

set -e -u -x

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

mkdir -p $BUILD_DIR/assets
cp -a fly/fly_linux_amd64 $BUILD_DIR/assets/fly
chmod +x $BUILD_DIR/assets/fly

cd $GOPATH/src/github.com/concourse/concourse-pipeline-resource

go install ./vendor/github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

./scripts/build

cp -a assets/ Dockerfile $BUILD_DIR
